### PR TITLE
Allow null column name to be to return complete arrays/objects in getColumn

### PR DESCRIPTION
**Pull request by izharaazmi**
Allow null column name to be to return complete arrays/objects in getColumn so that it behaves the same way as [array_column](http://php.net/manual/en/function.array-column.php) in `PHP 5.5+`

### CODE REVIEW

**Comment by mbabker** [comment]
Can you fix the test failure?

**Comment by mbabker** [comment]
Ahh, nevermind, it exists on master since a822f5c4b3f4b1e2934c65b7c6cc937768b20021

**Comment by izharaazmi** [comment]
Thanks!

I'd still have a look at that and try to fix it :)

**Comment by mbabker** [comment]
Already fixed it.  One of those cases where there was a test for a "bad" return.

**Pull request merged**
