### PR TITLE
[Feature] RegEx Utility

### PR DESCRIPTION
**Pull request by nibra**
### Summary of Changes

* Add a RegEx utility for maintainable creation of Regular Expressions.
    (Needed at least for URL parser implementation.)
* Move ArrayHelper documentation from README.md to docs directory.
* Fix small issues distracting static code analysis.

### Testing Instructions

See accompanied tests (100% coverage).

### Documentation Changes Required

Included.

### CODE REVIEW

**Comment by Llewellynvdm** [comment]
I am very exited to see the Regex class... smart :+1:

**Comment by nibra** [comment]
This will start with version 2.1.0, so the PR is against 2.0-dev instead of 1.x-dev (fka master)

**Review by Llewellynvdm — APPROVED** [review]

**Comment by Llewellynvdm** [comment]
@nibra will you be able to rebase this PR? and resolve the conflicts?

**Comment by nibra** [comment]
@Llewellynvdm Done

**Comment by Llewellynvdm** [comment]
Okay, I know this PR is not the cause of this... but I see there is an test on the ArrayHelper that fails.
```
PHPUnit 9.6.5 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.2-1ubuntu2.11
...............
Time: 00:00.017, Memory: 8.00 MB

Summary of non-successful tests:

Array Helper (Joomla\Utilities\Tests\ArrayHelper)
 ↩ Sort objects with data set "by casesensitive string ascending, french" [0.15 ms]
   │
   │ Locale 'fr_FR.utf8', 'fr_FR.UTF-8', 'fr_FR.UTF-8@euro', 'French_Standard', 'french', 'fr_FR', 'fre_FR' is not available.
   │
   │ /xxxxxx/joomla-framework/utilities/Tests/ArrayHelperTest.php:2420
   │

 ↩ Sort objects with data set "by caseinsensitive string, integer ascending" [0.04 ms]
   │
   │ Locale 'fr_FR.utf8', 'fr_FR.UTF-8', 'fr_FR.UTF-8@euro', 'French_Standard', 'french', 'fr_FR', 'fre_FR' is not available.
   │
   │ /xxxxx/joomla-framework/utilities/Tests/ArrayHelperTest.php:2420
   │

OK, but incomplete, skipped, or risky tests!
Tests: 93, Assertions: 96, Skipped: 2.
```
I can continue with the merge, but we will need to fix those, right!?

**Comment by nibra** [comment]
The test environment needs the French locale to be installed (on OS level, IIRC) for the test to work.

**Comment by Llewellynvdm** [comment]
Will be helpful if I actually read the error... 🤦

**Pull request merged**
